trigger:
  branches:
    include:
      - main
  paths:
    include:
      - pos_frontend/**   # 👈 sirf frontend folder
    exclude:
      - pos_backend/**    # 👈 backend ignore

pool:
  name: pos_agent

variables:
  node_version: '22.x'
  app_name: '$(retailflow-pos-app)'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

- script: |
    echo AFTER INSTALL:
    node -v
    where node
  displayName: 'Check Node After Install'

  
- script: |
    cd pos_frontend
    npm install -g @angular/cli
    npm install
  displayName: 'Install Dependencies'

- script: |
    cd pos_frontend
    ng build --configuration production
  displayName: 'Build Angular App'

- script: |
    copy pos_frontend/src/web.config pos_frontend/dist/browser/web.config
  displayName: 'Copy web.config'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'pos_frontend/dist/browser'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
  displayName: 'Archive Files'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
    artifactName: 'drop'
  displayName: 'Publish Artifact'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'pos_connection'
    appName: '$(retailflow-pos-app)'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
  displayName: 'Deploy to Azure'