trigger:
  branches:
    include:
      - main
  paths:
    include:
      - pos_frontend/**

pool:
  name: pos_agent

variables:
  node_version: '20.x'   

steps:

# 1️⃣ Install Node
- task: NodeTool@1
  inputs:
    versionSpec: '$(node_version)'

# 2️⃣ Install dependencies (clean install)
- script: |
    cd pos_frontend
    npm ci
  displayName: 'Install Dependencies'

# 3️⃣ Debug (VERY IMPORTANT - ek baar run karo)
- script: |
    cd pos_frontend
    dir
    dir node_modules
  displayName: 'Debug node_modules'

# 4️⃣ Build Angular (NO global CLI)
- script: |
    cd pos_frontend
    npx ng build --configuration production
  displayName: 'Build Angular'

# 5️⃣ Publish artifact
- publish: pos_frontend/dist
  artifact: angular_drop
  displayName: 'Publish Angular Build Artifact'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'pos_connection'
    appName: 'retailflow-pos'
    package: 'pos_frontend/dist'  