trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
# Install .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.x'

# Restore
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Azure for Students(3e106156-62e6-4695-a4c9-ab21ab8be451)'
    command: 'build'
- script: dotnet restore pos_backend
  displayName: 'Restore Backend'

# Build
- script: dotnet build pos_backend --configuration $(buildConfiguration)
  displayName: 'Build Backend'

# Publish
- script: dotnet publish pos_backend --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish Backend'

# Artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'pos_connection'   
    appName: 'pos-web-api'
    package: '$(Build.ArtifactStagingDirectory)'
- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students(3e106156-62e6-4695-a4c9-ab21ab8be451)'
    appType: 'apiApp'
    WebAppName: 'pos_service'
    deployToSlotOrASE: true
    ResourceGroupName: 'pos-web-api'
    SlotName: 'production'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'    