trigger:
  branches:
    include:
      - main
  paths:
    include:
      - pos_frontend/**

pool:
  name: pos_agent   # ✅ self-hosted

variables:
  node_version: '20.x'

steps:

# 1️⃣ Node install
- task: UseNode@1
  inputs:
    version: '$(node_version)'

# 2️⃣ Install dependencies
- script: |
    cd pos_frontend
    npm ci
  displayName: 'Install Dependencies'

# 3️⃣ Build Angular
- script: |
    cd pos_frontend
    npx ng build --configuration production
  displayName: 'Build Angular'

# 4️⃣ Copy dist files
- task: CopyFiles@2
  inputs:
    SourceFolder: 'pos_frontend/dist'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# 5️⃣ Deploy to Azure App Service 🚀
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'pos_connection'
    appName: 'retailflow-pos-app'
    package: '$(Build.ArtifactStagingDirectory)'