trigger:
- main

pool:
  name: window-latest   

variables:
  buildConfiguration: 'Release'

steps:

# Install .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.0'

# Restore
- script: dotnet restore pos_backend
  displayName: 'Restore Backend'

# Build
- script: dotnet build pos_backend --configuration $(buildConfiguration)
  displayName: 'Build Backend'

# Publish
- script: dotnet publish pos_backend --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish Backend'

# Artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'